# This workflow will build a package using Maven and then publish it to GitHub packages

name: Release

on:
   workflow_dispatch:
     inputs:
       name:
         description: 'Git name'
         required: true
         default: 'Phillip Kruger'
       email:
         description: 'Git email'
         required: true
         default: 'phillip.kruger@gmail.com'  
       username:
         description: 'Runtime Server User'
         required: true
         default: 'pkruger'
       password:
         description: 'Runtime Server Password'
         required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
    
    - name: Configure Git  
      run: |
        git config user.email "${{ github.event.inputs.email }}"
        git config user.name "${{ github.event.inputs.name }}"    
      
    - name: Perform release
      run: mvn -Dgit.username=${{ github.actor }} -Dgit.password=${{ secrets.GITHUB_TOKEN }} release:prepare release:perform --file pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Get tag
      id: gettag
      uses: WyriHaximus/github-action-get-previous-tag@v1
    
    - name: SSH to Server
      uses: appleboy/scp-action@master
      with:
        host: "92.205.31.205"
        username: ${{ github.event.inputs.username }}
        password: ${{ github.event.inputs.password }}
        source: "${{ github.workspace }}/target/weeklystatus.tar.gz"
        strip_components: 3
        target: "staging/weeklystatus/${{ steps.gettag.outputs.tag }}/"        